name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./ci-example
      run: npm install
    - name: Run tests
      working-directory: ./ci-example
      run: npm run test:unit